AnuncioWebMotors/Models/Anuncio.cs
using System.ComponentModel.DataAnnotations;

namespace AnuncioWebMotors.Models
{
    public class Anuncio
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Necessário escolher uma Marca")]
        [StringLength(45)]
        public string Marca { get; set; }

        [Required(ErrorMessage = "Necessário escolher um Modelo")]
        [StringLength(45)]
        public string Modelo { get; set; }

        [Required(ErrorMessage = "Necessário escolher uma Versão")]
        public string Versao { get; set; }
        [Required(ErrorMessage = "Necessário informar o ano")]
        [RegularExpression(@"^(19|[2-9][0-9])\d{2}$", ErrorMessage = "Informe o ano entre 1900 e 9999")] // anos de 1900 - 9999
        public int Ano { get; set; }
        [Required(ErrorMessage = "Necessários informar KM")]
        [RegularExpression(@"^\d*\.{0,1}\d+$", ErrorMessage = "Informe apenas números positivos")] // só numeros positivos
        public int Quilometragem { get; set; }
        [Required(ErrorMessage = "Necessário informar Observação")]
        public string Observacao { get; set; }

    }

}

AnuncioWebMotors/Models/ErrorViewModel.cs
using System;

namespace AnuncioWebMotors.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnuncioWebMotors/Models/Marca.cs
namespace AnuncioWebMotors.Models
{
    public class Marca
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

AnuncioWebMotors/Models/Modelo.cs
namespace AnuncioWebMotors.Models
{
    public class Modelo
    {
        public int ID { get; set; }
        public int MakeID { get; set; }
        public string Name { get; set; }
    }
}

AnuncioWebMotors/Models/Veiculo.cs
namespace AnuncioWebMotors.Models
{
    public class Veiculo
    {
        public int ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Version { get; set; }
        public string Image { get; set; }
        public int KM { get; set; }
        public double Price { get; set; }
        public int YearModel { get; set; }
        public int YearFab { get; set; }
        public string Color { get; set; }
    }
}

AnuncioWebMotors/Models/Versao.cs
namespace AnuncioWebMotors.Models
{
    public class Versao
    {
        public int ID { get; set; }
        public int ModeloID { get; set; }
        public string Name { get; set; }
    }
}

AnuncioWebMotors/Controllers/AnunciosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AnuncioWebMotors.Data;
using AnuncioWebMotors.Models;
using AnuncioWebMotors.Repositories;

namespace AnuncioWebMotors.Controllers
{
    public class AnunciosController : Controller
    {
        private readonly AnuncioContext _context;
        private readonly IAnuncioRepository _anuncioRepository;

        public AnunciosController(AnuncioContext context, IAnuncioRepository anuncioRepository)
        {
            _context = context;
            _anuncioRepository = anuncioRepository;
        }


        public async Task<IActionResult> Index()
        {
            var anuncios = await _anuncioRepository.GetListaAnuncios();
            return View(anuncios);
        }
        // GET: Anuncios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _anuncioRepository.GetAnuncioPorId(id);

            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // GET: Anuncios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Anuncios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Marca,Modelo,Versao,Ano,Quilometragem,Observacao")] Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                await _anuncioRepository.GravaAnuncioAsync(anuncio);
                return RedirectToAction(nameof(Index));
            };
            return View(anuncio);
        }

        // GET: Anuncios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _anuncioRepository.GetAnuncioPorId(id);
            if (anuncio == null)
            {
                return NotFound();
            }
            return View(anuncio);
        }

        // POST: Anuncios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Marca,Modelo,Versao,Ano,Quilometragem,Observacao")] Anuncio anuncio)
        {
            if (id != anuncio.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _anuncioRepository.Atualizar(anuncio);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnuncioExists(anuncio.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anuncio);
        }

        // GET: Anuncios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _anuncioRepository.BuscarAnuncioPorId(id);
            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // POST: Anuncios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anuncio = await _anuncioRepository.GetAnuncioPorId(id);
            await _anuncioRepository.Excluir(anuncio);
            return RedirectToAction(nameof(Index));
        }

        private bool AnuncioExists(int id)
        {
            return _anuncioRepository.Existe(id);
        }
    }
}

AnuncioWebMotors/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AnuncioWebMotors.Models;

namespace AnuncioWebMotors.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AnuncioWebMotors/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnuncioWebMotors.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AnuncioWebMotors.Controllers
{
    public class VeiculoController : Controller
    {
        protected readonly IVeiculoService veiculoService;

        public VeiculoController(IVeiculoService veiculoService)
        {
            this.veiculoService = veiculoService;

        }


        public IActionResult IncluirAnuncio()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetListaMarcas()
        {
            var marcas = await veiculoService.GetMarcasAsync();
            return StatusCode(200, marcas);
        }

        [HttpGet]
        public async Task<IActionResult> GetListaModelos(int idMarca)
        {
            var modelos = await veiculoService.GetModelosAsync(idMarca);
            return StatusCode(200, modelos);
        }

        [HttpGet]
        public async Task<IActionResult> GetListaVersao(int idVersao)
        {
            var versoes = await veiculoService.GetVersaoAsync(idVersao);
            return StatusCode(200, versoes);
        }
    }
}

AnuncioWebMotors/Views/Anuncios/Create.cshtml
@model AnuncioWebMotors.Models.Anuncio

@{
    ViewData["Title"] = "Incluir Anúncio";
}

<h1>Incluir Novo Anúncio</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div id="mensagem_error"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="marca">Marca:</label>
                <select id="marca" asp-for="Marca" class="form-control">
                </select>
            </div>

            <div class="form-group">
                <label for="modelo">Modelo:</label>
                <select id="modelo" asp-for="Modelo" class="form-control">
                </select>
            </div>

            <div class="form-group">
                <label for="versao">Versão:</label>
                <select id="versao" asp-for="Versao" class="form-control">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quilometragem" class="control-label"></label>
                <input asp-for="Quilometragem" class="form-control" />
                <span asp-validation-for="Quilometragem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observacao" class="control-label"></label>
                <input asp-for="Observacao" class="form-control" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts
{
    <script src="~/js/services.js"></script>
}

AnuncioWebMotors/Views/Anuncios/Delete.cshtml
@model AnuncioWebMotors.Models.Anuncio

@{
    ViewData["Title"] = "Exluir";
}

<h1>Exluir Anúncio</h1>

<h3>Deseja Excluir este Anúncio?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Versao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a Lista</a>
    </form>
</div>

AnuncioWebMotors/Views/Anuncios/Details.cshtml
@model AnuncioWebMotors.Models.Anuncio

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes do Anúncio</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Versao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Editar</a> |
    <a asp-action="Index">Voltar para a Lista</a>
</div>

AnuncioWebMotors/Views/Anuncios/Edit.cshtml
@model AnuncioWebMotors.Models.Anuncio

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar Anúncio</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div id="mensagem_error"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <select id="marca" asp-for="Marca" class="form-control">
                </select>
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <select id="modelo" asp-for="Modelo" class="form-control">
                </select>
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Versao" class="control-label"></label>
                <select id="versao" asp-for="Versao" class="form-control">
                </select>
                <span asp-validation-for="Versao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quilometragem" class="control-label"></label>
                <input asp-for="Quilometragem" class="form-control" />
                <span asp-validation-for="Quilometragem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observacao" class="control-label"></label>
                <input asp-for="Observacao" class="form-control" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts
{
    <script src="~/js/services.js"></script>
}

AnuncioWebMotors/Views/Anuncios/Index.cshtml
@model IEnumerable<AnuncioWebMotors.Models.Anuncio>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Anúncios</h1>

<p>
    <a asp-action="Create">Incluir Novo Anúncio</a>
</p>



<hr />
<h4>Anúncios Cadastrados</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Versao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quilometragem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Versao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quilometragem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Observacao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

AnuncioWebMotors/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Webmotors</h1>
    <p>Teste prático de Backend Webmotors</p>
    <p>Objetivo do teste é chegar em uma tela básica de crud de anúncios</p>
    <p>Bem como anúncios da tabela com consumo das informações de marca, modelo e versão via webservice</p>
    <p>Utilize o Menu superior</p>
</div>

AnuncioWebMotors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnuncioWebMotors</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnuncioWebMotors</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anuncios" asp-action="Index">Incluir Anúncio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AnuncioWebMotors - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>